version: "3"
services:
    janus:
        build:
            context: ./docker/docker-janus
        image: "ptsneves/airborneprojects:janus"
        network_mode: host
        ports:
            - "8088:8088"
            - "6004-6200:6004-6200/udp"
        volumes:
            - live-video-storage:/var/live-video-storage
        logging:
            options:
                max-file: "5"
                max-size: "100m"
    web:
        build:
            context: .
            dockerfile: docker/docker-dotnet/Dockerfile
        image: "ptsneves/airborneprojects:release-master"
        network_mode: host
        ports:
            - "5000:5000"
        depends_on:
            - "database"
            - "janus"
        restart: on-failure
        volumes:
            - live-video-storage:/var/live-video-storage
        logging:
            options:
                max-file: "5"
                max-size: "100m"
    database:
        image: mysql:latest
        network_mode: host
        ports:
            - "3306:3306"
        environment:
          - "MYSQL_DATABASE=master"
          - "MYSQL_RANDOM_ROOT_PASSWORD=yes"
          - "MYSQL_USER=sa"
          - "MYSQL_PASSWORD=XXXXX"
        # volumes:
            # mysql-volume:/var/lib/mysql
    letsencrypt:
         build:
             context: ./docker/docker-letsencrypt
         image: ptsneves/airborneprojects:letsencrypt
         volumes:
             - certificates-volume:/etc/letsencrypt
    nginx:
         network_mode: host
         build:
             context: ./docker/docker-nginx
         image: ptsneves/airborneprojects:nginx
         volumes:
             - certificates-volume:/etc/letsencrypt
         logging:
             options:
                 max-file: "5"
                 max-size: "100m"
volumes:
    certificates-volume:
    live-video-storage:
    mysql-volume:
