version: "3"
services:
    janus:
        build:
            context: ./docker-janus
        image: "ptsneves/airborneprojects:janus"
        network_mode: host
        ports:
            - "8088:8088"
            - "6004-6200:6004-6200/udp"
        volumes:
            - live-video-storage:/var/live-video-storage
    web:
        build:
            context: .
            dockerfile: docker-dotnet/Dockerfile
        image: "ptsneves/airborneprojects:release-master"
        network_mode: host
        ports:
            - "5000:5000"
        depends_on:
            - "database"
            - "janus"
        restart: on-failure
        volumes:
            - live-video-storage:/var/live-video-storage
    database:
        image: mysql:latest
        network_mode: host
        ports:
            - "3306:3306"
        environment:
          - "MYSQL_DATABASE=master"
          - "MYSQL_RANDOM_ROOT_PASSWORD=yes"
          - "MYSQL_USER=sa"
          - "MYSQL_PASSWORD=XXXXX"
volumes:
    live-video-storage:
