version: "3"
services:
    janus:
        build:
            context: ./docker/docker-janus
        image: "ptsneves/airborneprojects:janus"
        # We need host mode to expose the ports for the sfu, otherwise video will not
        # work. Declaring a huge range of ports is not really feasible as it takes a long
        # time with docker
        network_mode: host
        volumes:
            - live-video-storage:/var/live-video-storage
        logging:
            options:
                max-file: "5"
                max-size: "100m"
    web:
        container_name: drohub-web
        extra_hosts:
          # new trick so that nginx has access to janus which has network_host mode
          # see https://stackoverflow.com/a/24326540/227990
          # this makes a dependency on docker 18.03+
          - "host.docker.internal:host-gateway"
        build:
            context: .
            dockerfile: docker/docker-dotnet/Dockerfile
        image: "ptsneves/airborneprojects:release-master"
        environment:
#           The following variables are to be overriden by .env file
#           The reason for the DHUB_ prefix is that code looks for it and
#           automatically forwards environmental variables with such prefix
#           to the configurations and overrides them.
#           In our case it means that the configuration in appsettings.json
#           Conf.ConnectionStrings.DroHubConnectionMySQL gets overwritten
#           As the configurations in appsettings for secrets mostly have @@ENV@@
#           placeholder we need to forcefully overwrite these configurations or
#           things will not work properly.
            DHUB_ConnectionStrings__DroHubConnectionMySQL: 'Server=drohub-database;port=3306;database=master'
            DHUB_ConnectionStrings__MysqlUser: "${DHUB_ConnectionStrings__MysqlUser?}"
            DHUB_ConnectionStrings__MysqlPassword: "${DHUB_ConnectionStrings__MysqlPassword?}"
            DHUB_MailJetEmailSender__APIKey: "${DHUB_MailJetEmailSender__APIKey?}"
            DHUB_MailJetEmailSender__APISecret: "${DHUB_MailJetEmailSender__APISecret?}"
            DHUB_RepositoriesConfiguration__GoogleMapsAPIKey: "${DHUB_RepositoriesConfiguration__GoogleMapsAPIKey?}"
            DHUB_JanusServiceOptions__AdminKey: "${DHUB_JanusServiceOptions__AdminKey?}"
            DHUB_JanusServiceOptions__Address: "http://host.docker.internal"
        ports:
            - "5000:5000"
        depends_on:
            - "database"
            - "janus"
        restart: on-failure
        volumes:
            - live-video-storage:/var/live-video-storage
        logging:
            options:
                max-file: "5"
                max-size: "100m"
    database:
        container_name: drohub-database
        image: mysql:latest
        ports:
            - "3306:3306"
        environment:
          MYSQL_DATABASE: "master"
          MYSQL_RANDOM_ROOT_PASSWORD: "yes"
#         Mandatory secrets
          MYSQL_USER: "${DHUB_ConnectionStrings__MysqlUser?}"
          MYSQL_PASSWORD: "${DHUB_ConnectionStrings__MysqlPassword?}"
        # volumes:
            # mysql-volume:/var/lib/mysql
    letsencrypt:
         environment:
             - DOMAIN=localhost
         build:
             context: ./docker/docker-letsencrypt
         image: ptsneves/airborneprojects:letsencrypt
         volumes:
             - certificates-volume:/etc/letsencrypt
    nginx:
         extra_hosts:
         # new trick so that nginx has access to janus which has network_host mode
         # see https://stackoverflow.com/a/24326540/227990
         # this makes a dependency on docker 18.03+
            - "host.docker.internal:host-gateway"
         ports:
             -   "443:443"
             -   "80:80"
         build:
             context: ./docker/docker-nginx
         image: ptsneves/airborneprojects:nginx
         volumes:
             - certificates-volume:/etc/letsencrypt
         logging:
             options:
                 max-file: "5"
                 max-size: "100m"
         environment:
             - DOMAIN_NAME
             - SSL_CERTIFICATE_PATH=/etc/letsencrypt/live/${DOMAIN_NAME?}/fullchain.pem
             - SSL_CERTIFICATE_KEY_PATH=/etc/letsencrypt/live/${DOMAIN_NAME?}/privkey.pem
             - TIMEOUT_SECONDS=100
             - DEPENDENCY_FQDN=drohub-web
             - DEPENDENCY_PORT=5000
volumes:
    certificates-volume:
        driver: local
    live-video-storage:
        driver: local
    mysql-volume:
        driver: local