version: "3"
services:
    janus:
        image: "ptsneves/airborneprojects:janus"
        network_mode: host
        ports:
            - "8088:8088"
            - "6004-6200:6004-6200/udp"
        depends_on:
            - "web"
    web:
        image: "ptsneves/airborneprojects:release-master"
        network_mode: host
        ports:
            - "5000:5000"